# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Lint and unit test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: dschep/install-pipenv-action@v1
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pip install flake8
        flake8 dublinbike-data-fetcher
    - name: Test with pytest
      run: |
        pip install pytest
        pytest dublinbike-data-fetcher
